export const myProjects = [
  {
    projectTitle: "Hardtask",
    projectDesc: "Web Design / 2022",
    category: ["css","javascript"],
    imgPath: "./images/work-13.jpg",
    link: "https://haardtask.netlify.app/",
  },
  {
    projectTitle: "My Portfolio",
    projectDesc: "Web Design / 2025",
    category: ["react"],
    imgPath: "./images/work-35.jpg",
    link: "https://ashrafx.netlify.app/",
  },
  {
    projectTitle: "Drwazat Alsafat",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-29.jpg",
    link: "https://drwazatalsafat.netlify.app/",
  },
  {
    projectTitle: "Esaal",
    projectDesc: "Web Design / 2019",
    category: ["css","javascript"],
    imgPath: "./images/work-6.jpg",
    link: "https://esaal.netlify.app/",
  },
  {
    projectTitle: "Marino Butchery",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-28.jpg",
    link: "https://marinobutchery.netlify.app/",
  },
  {
    projectTitle: "Alkuwaityah",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-26.jpg",
    link: "https://alkuwaityah.netlify.app/",
  },
  {
    projectTitle: "Magic Touch",
    projectDesc: "Web Design / 2022",
    category: ["css"],
    imgPath: "./images/work-34.jpg",
    link: "https://maggictouch.netlify.app/",
  },
  {
    projectTitle: "Vchanic",
    projectDesc: "Web Design / 2021",
    category: ["css","javascript"],
    imgPath: "./images/work-32.jpg",
    link: "https://vchanic.netlify.app/",
  },
  {
    projectTitle: "Media Academy",
    projectDesc: "Web Design / 2019",
    category: ["css","javascript"],
    imgPath: "./images/work-12.jpg",
    link: "https://mediaacademy.netlify.app/",
  },
  {
    projectTitle: "Expo 35",
    projectDesc: "Web Design / 2020",
    category: ["css","javascript"],
    imgPath: "./images/work-17.jpg",
    link: "https://expo35.netlify.app/",
  },
  {
    projectTitle: "Man Boutique",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-27.jpg",
    link: "https://manboutique.netlify.app/",
  },
  {
    projectTitle: "ksmcq8",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-30.jpg",
    link: "https://ksmcq8.netlify.app/",
  },
  {
    projectTitle: "Dar Elmaane",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-24.jpg",
    link: "https://darelmaane.netlify.app/",
  },
  {
    projectTitle: "Kaabi Stores",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-33.jpg",
    link: "https://kaabistores.netlify.app/",
  },
  {
    projectTitle: "Soko",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-25.jpg",
    link: "https://sokoo.netlify.app/",
  },
  {
    projectTitle: "Diva Abaya",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-19.jpg",
    link: "https://divaabaya.netlify.app/",
  },
  {
    projectTitle: "Churro Break",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-18.jpg",
    link: "https://churrobreak.netlify.app/",
  },
  {
    projectTitle: "Hesabi",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-7.jpg",
    link: "https://hesabi.netlify.app/",
  },
  {
    projectTitle: "4Mazad",
    projectDesc: "Web Design / 2019",
    category: ["css","javascript"],
    imgPath: "./images/work-9.jpg",
    link: "https://4mazad.netlify.app/",
  },
  {
    projectTitle: "Basateen",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-11.jpg",
    link: "https://basateen.netlify.app/",
  },

  {
    projectTitle: "Chef 55",
    projectDesc: "Web Design / 2020",
    category: ["css","javascript"],
    imgPath: "./images/work-2.jpg",
    link: "https://chef55.netlify.app/",
  },
  {
    projectTitle: "Al Dibaji",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-31.jpg",
    link: "https://aldibaji.netlify.app/",
  },
  {
    projectTitle: "Netlet",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-3.jpg",
    link: "https://netlet.netlify.app/",
  },
  {
    projectTitle: "4saleQ8",
    projectDesc: "Web Design / 2019",
    category: ["css","javascript"],
    imgPath: "./images/work-4.jpg",
    link: "https://4saleq8.netlify.app/",
  },
  {
    projectTitle: "Dar Shaghf",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-5.jpg",
    link: "https://darshaghf.netlify.app/",
  },
  {
    projectTitle: "Al Sanea",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-20.jpg",
    link: "https://alsanea.netlify.app/",
  },
  {
    projectTitle: "Adaawer",
    projectDesc: "Web Design / 2020",
    category: ["css","javascript"],
    imgPath: "./images/work-21.jpg",
    link: "https://adaawer.netlify.app/",
  },
  {
    projectTitle: "Dr Eidan",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-22.jpg",
    link: "https://dreidan.netlify.app/",
  },
  {
    projectTitle: "Madi Legal Group",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-23.jpg",
    link: "https://madilegal.netlify.app/",
  },
  {
    projectTitle: "Artdeco",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-8.jpg",
    link: "https://artdeco.netlify.app/",
  },
  {
    projectTitle: "Square Rys",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-10.jpg",
    link: "https://squarerys.netlify.app/",
  },
  {
    projectTitle: "Tswq",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-14.jpg",
    link: "https://tswq.netlify.app/",
  },
  {
    projectTitle: "Memovie",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-15.jpg",
    link: "https://memovie.netlify.app/",
  },
];
