export const myProjects = [
  {
    projectTitle: "Hardtask",
    projectDesc: "Web Design / 2022",
    category: ["css"],
    imgPath: "./images/work-13.jpg",
  },
  {
    projectTitle: "Drwazat Alsafat",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-29.jpg",
  },
  {
    projectTitle: "Esaal",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-6.jpg",
  },
  {
    projectTitle: "Marino Butchery",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-28.jpg",
  },
  {
    projectTitle: "Alkuwaityah",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-26.jpg",
  },
  {
    projectTitle: "Magic Touch",
    projectDesc: "Web Design / 2022",
    category: ["css"],
    imgPath: "./images/work-34.jpg",
  },
  {
    projectTitle: "Vchanic",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-32.jpg",
  },
  {
    projectTitle: "Media Academy",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-12.jpg",
  },
  {
    projectTitle: "Expo 35",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-17.jpg",
  },
  {
    projectTitle: "Man Boutique",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-27.jpg",
  },
  {
    projectTitle: "ksmcq8",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-30.jpg",
  },
  {
    projectTitle: "Dar Elmaane",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-24.jpg",
  },
  {
    projectTitle: "Kaabi Stores",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-33.jpg",
  },
  {
    projectTitle: "Soko",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-25.jpg",
  },
  {
    projectTitle: "Diva Abaya",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-19.jpg",
  },
  {
    projectTitle: "Churro Break",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-18.jpg",
  },
  {
    projectTitle: "Hesabi",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-7.jpg",
  },
  {
    projectTitle: "4Mazad",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-9.jpg",
  },
  {
    projectTitle: "Basateen",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-11.jpg",
  },

  {
    projectTitle: "Chef 55",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-2.jpg",
  },
  {
    projectTitle: "Al Dibaji",
    projectDesc: "Web Design / 2021",
    category: ["css"],
    imgPath: "./images/work-31.jpg",
  },
  {
    projectTitle: "Netlet",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-3.jpg",
  },
  {
    projectTitle: "4saleQ8",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-4.jpg",
  },
  {
    projectTitle: "Dar Shaghf",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-5.jpg",
  },
  {
    projectTitle: "Al Sanea",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-20.jpg",
  },
  {
    projectTitle: "Adaawer",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-21.jpg",
  },
  {
    projectTitle: "Dr Eidan",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-22.jpg",
  },
  {
    projectTitle: "Madi Legal Group",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-23.jpg",
  },
  {
    projectTitle: "Artdeco",
    projectDesc: "Web Design / 2020",
    category: ["css"],
    imgPath: "./images/work-8.jpg",
  },
  {
    projectTitle: "Square Rys",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-10.jpg",
  },
  {
    projectTitle: "Tswq",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-14.jpg",
  },
  {
    projectTitle: "Memovie",
    projectDesc: "Web Design / 2019",
    category: ["css"],
    imgPath: "./images/work-15.jpg",
  },
];